package codegen

import "text/template"

// GoTmpl is template for generating Go code from app-error-codes configuration.
var GoTmpl = template.Must(template.New("goTemplate").Funcs(template.FuncMap{
	"pascalCase": pascalCase,
	"replace":    replace,
	"derefBool":  func(b *bool) bool { return *b },
}).Parse(goTmpl))

const goTmpl = `// Code generated by apperr. DO NOT EDIT.

package gen

import (
	"text/template"

	"github.com/mlukasik-dev/grpcerr"
)
{{ range $key, $value := .Uses }}
var {{ $key }} = struct {
	{{- range $value }}
	{{ pascalCase .Name }} grpcerr.GrpcErr
	{{- end}}
}{
	{{- range $value }}
	grpcerr.GrpcErr{
		Name: "{{ .Name }}",
		Title: "{{ replace .Title }}",
		Message: {{ if derefBool .Options.Template }}""{{ else }}"{{ replace .Message }}"{{ end }},
		MessageTmpl: {{ if derefBool .Options.Template }}template.Must(template.New("").Parse("{{ replace .Message }}")){{ else }}nil{{ end }},
		Options: grpcerr.Options{
			Template: {{ .Options.Template }},
		}},
	{{- end}}	
}
{{- end}}
`
